2020-05-29 07:54:23,658 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Projects/cve-search/web/minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %}{{ _('Most recent entries') }}{% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 07:54:33,357 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Projects/cve-search/web/minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %}{{ _('Most recent entries') }}{% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 07:54:39,380 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Projects/cve-search/web/minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %}{{ _('Most recent entries') }}{% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 07:54:42,694 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Projects/cve-search/web/minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %}{{ _('Most recent entries') }}{% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 08:13:31,686 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %} == {{ _('Most recent entries') }} {% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 08:13:51,557 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %} == {{ _('Most recent entries') }} {% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 08:13:52,621 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %} == {{ _('Most recent entries') }} {% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 08:19:26,259 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 292, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - CVE-Search</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %} == {{ _('Most recent entries') }} {% endblock %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-29 11:17:09,396 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 293, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - {{ _('CERT epsilon') }}</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %} {{ _('Most recent entries') }} {% endblock %}
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/ext.py", line 150, in gettext
    rv = __context.call(func, __string)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask_babel/__init__.py", line 110, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask_babel/__init__.py", line 221, in get_translations
    [get_locale()],
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask_babel/__init__.py", line 251, in get_locale
    rv = babel.locale_selector_func()
TypeError: get_locale() missing 1 required positional argument: 'self'
2020-05-29 11:21:34,029 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 293, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/index.html", line 1, in top-level template code
    {% extends 'layouts/master-page' %}
  File "/home/user/Projects/cve-search/web/templates/layouts/master-page", line 39, in top-level template code
    <title>{% block title %}{% endblock %} - {{ _('CERT epsilon') }}</title>
  File "/home/user/Projects/cve-search/web/templates/index.html", line 2, in block "title"
    {% block title %} {{ _('Most recent entries') }} {% endblock %}
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/ext.py", line 150, in gettext
    rv = __context.call(func, __string)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask_babel/__init__.py", line 110, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask_babel/__init__.py", line 221, in get_translations
    [get_locale()],
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask_babel/__init__.py", line 251, in get_locale
    rv = babel.locale_selector_func()
TypeError: get_locale() missing 1 required positional argument: 'self'
2020-05-29 11:24:26,744 - web.api - ERROR - Exception on /lang/en [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 508, in change_language
    return redirect(url_for('index.html', cve=cve, message=message, r=0, **self.args))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index.html' with values ['cve', 'listLogin', 'message', 'minimal', 'pageLength', 'r']. Did you mean 'index' instead?
2020-05-29 11:30:37,887 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 298, in index
    return render_template('index.html', cve=cve, message=message, r=0, **self.args)
NameError: name 'message' is not defined
2020-05-29 11:34:21,415 - web.api - ERROR - Exception on /lang/en [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 513, in change_language
    return render_template('.index', cve=cve, message=message, r=0, **self.args)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .index
2020-05-29 13:03:32,230 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 294, in index
    print(session['message'])
NameError: name 'session' is not defined
2020-05-29 13:03:38,860 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 294, in index
    print(session['message'])
NameError: name 'session' is not defined
2020-05-29 13:03:57,486 - web.api - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/minimal.py", line 294, in index
    print(session['message'])
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/sessions.py", line 84, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'message'
2020-06-03 09:00:07,126 - web.api - ERROR - Exception on /link/oval.family/unix [GET]
Traceback (most recent call last):
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Projects/cve-search/web/../web/minimal.py", line 398, in link
    value=value, cve=cve, stats=stats, minimal=self.minimal)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/user/Projects/epsilon_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Projects/cve-search/web/templates/linked.html", line 2, in template
    {% block title %}{{ _('CVE's linked by') }} {{field}}{% endblock %}
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 's'
